services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"

  web:
    image: kyczak/chatapp:latest
    container_name: chatapp
    restart: always
    depends_on:
      - redis
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"