# Generated by Django 4.2.7 on 2024-01-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
