# Generated by Django 4.2.7 on 2024-01-22 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_room_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='additional_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
