# Generated by Django 4.2.7 on 2024-01-23 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_room_additional_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="additional_users",
            new_name="users",
        ),
        migrations.RemoveField(
            model_name="room",
            name="author",
        ),
        migrations.RemoveField(
            model_name="room",
            name="user",
        ),
    ]
