# Generated by Django 4.2.7 on 2024-01-24 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0014_profile_delete_userprofile_alter_room_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
