# Generated by Django 4.2.7 on 2024-05-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0017_alter_message_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.CharField(max_length=1000000),
        ),
    ]
