name: image-builder

on:
  push:
    branches:
      - "master"
      - "beta"
  workflow_dispatch:

env:
  TEST_TAG: kyczak/chatapp:test
  LATEST_TAG: kyczak/chatapp:latest
  BETA_TAG: kyczak/chatapp:beta

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          docker run --rm --entrypoint "" ${{ env.TEST_TAG }} python -c "print('Test successful')"
        
      - name: Build and push for master
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ env.LATEST_TAG }}

      - name: Build and push for beta
        if: github.ref == 'refs/heads/beta'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ env.BETA_TAG}}